export const INITIAL_CATEGORY = 'INITIAL_CATEGORY'
export const INITIAL_PRODUCT = 'INITIAL_PRODUCT'
export const INITIAL_USER_DETAIL = 'INITIAL_USER_DETAIL'
export const LOGIN_ACTIVE = 'LOGIN_ACTIVE'
export const ACTIVE_USER = 'ACTIVE_USER'
export const PRODUCT_POP_ACTIVE ="PRODUCT_POP_ACTIVE"
export const CURRENT_PRODUCT = 'CURRENT_PRODUCT'